# Generated by Django 4.1.7 on 2023-03-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('periodo', models.CharField(max_length=50)),
            ],
        ),
    ]
