# Generated by Django 4.1.7 on 2023-03-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('carrera', models.CharField(max_length=150)),
                ('abreviatura', models.CharField(max_length=50)),
            ],
        ),
    ]
