# Generated by Django 4.1.7 on 2023-03-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_noticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(max_length=250)),
                ('lugar', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('link', models.CharField(max_length=599)),
                ('image', models.ImageField(default='evento.jpg', upload_to='')),
            ],
        ),
    ]
