# Generated by Django 4.1.7 on 2023-03-03 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('integrantes', models.CharField(max_length=450)),
                ('asesor', models.CharField(max_length=150)),
                ('ciclo', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=599)),
                ('resumen', models.TextField()),
                ('image', models.ImageField(default='estudiantes.jpg', upload_to='')),
                ('image2', models.ImageField(default='estudiantes.jpg', upload_to='')),
                ('image3', models.ImageField(default='estudiantes.jpg', upload_to='')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.carrera')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.periodo')),
            ],
        ),
    ]
